Wnguye03 set up for GitHub actions
oslabs-beta/NextInspect pull request #3
Opened 2023-05-24 02:36 UTC by wnguye03

## Overview

Issue Type

- [ ] Bug
- [ ] Feature
- [x] Tech Debt

Description
Initial set up for GitHub actions

2023-05-24 03:16 UTC, YouruiR requested changes

2023-05-24 03:16 UTC, YouruiR commented on .github/pull_request_template.md
> +
Is the PR template supposed to show? I made this a hidden file but it is showing in your PR but not the other previous merged PR's

2023-05-25 02:52 UTC, YouruiR approved these changes

2023-05-25 02:52 UTC, davidan1989 approved these changes

2023-05-25 02:52 UTC, merged